import type { Doctor } from './types';

export const doctors: Doctor[] = [
  {
    id: '1',
    name: 'Dr. Emily Carter',
    specialty: 'Cardiologist',
    location: 'Metropolis General Hospital',
    rating: 4.9,
    reviews: 124,
    imageId: 'doctor-1',
    bio: 'Dr. Emily Carter is a board-certified cardiologist with over 15 years of experience in treating complex heart conditions. She is known for her patient-centric approach and dedication to cardiovascular research.',
    experience: 15,
    consultationFeeOnsite: 1500,
    consultationFeeOnline: 1200,
  },
  {
    id: '2',
    name: 'Dr. Benjamin Lee',
    specialty: 'Neurologist',
    location: 'City Central Hospital',
    rating: 4.8,
    reviews: 98,
    imageId: 'doctor-2',
    bio: 'Dr. Benjamin Lee specializes in neurological disorders, including epilepsy and stroke. He is a leading expert in advanced neuro-imaging techniques and minimally invasive procedures.',
    experience: 12,
    consultationFeeOnsite: 1400,
    consultationFeeOnline: 1100,
  },
  {
    id: '3',
    name: 'Dr. Olivia Garcia',
    specialty: 'Pediatrician',
    location: "Sunnyvale Children's Clinic",
    rating: 5.0,
    reviews: 210,
    imageId: 'doctor-3',
    bio: 'Dr. Olivia Garcia has a passion for pediatric care and is beloved by her young patients and their families. She focuses on preventative care and holistic child development.',
    experience: 10,
    consultationFeeOnsite: 1000,
    consultationFeeOnline: 800,
  },
  {
    id: '4',
    name: 'Dr. Daniel Chen',
    specialty: 'Orthopedic Surgeon',
    location: 'Metropolis General Hospital',
    rating: 4.7,
    reviews: 85,
    imageId: 'doctor-4',
    bio: 'Dr. Daniel Chen is an orthopedic surgeon specializing in sports medicine and joint replacement. He uses cutting-edge technology to help patients regain mobility and return to their active lifestyles.',
    experience: 18,
    consultationFeeOnsite: 1600,
    consultationFeeOnline: 1300,
  },
];
